# Generated by Django 6.0.2 on 2026-03-06 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_telegram", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingPortal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=250)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Human-readable unique identifier for the portal",
                        max_length=250,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description shown in the portal intro message.",
                    ),
                ),
                (
                    "pinned_message_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Telegram message id of the pinned portal intro message.",
                        null=True,
                    ),
                ),
                (
                    "portal_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "max_mistakes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Maximum number of corrections per submission.",
                        null=True,
                    ),
                ),
                ("opens_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_portals",
                        to="django_telegram.telegramchat",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="PortalReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "common.language.en"),
                            ("es", "common.language.es"),
                        ],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("message_id", models.BigIntegerField(blank=True, null=True)),
                ("message_text", models.TextField(blank=True)),
                (
                    "reading_portal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_readings",
                        to="reading_portal.readingportal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReadingSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "common.language.en"),
                            ("es", "common.language.es"),
                        ],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("reading_message_id", models.BigIntegerField()),
                (
                    "reading_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("superseded", "Superseded"),
                        ],
                        default="pending",
                        max_length=40,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_submissions",
                        to="django_telegram.telegramgroupmember",
                    ),
                ),
                (
                    "reading_portal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_submissions",
                        to="reading_portal.readingportal",
                    ),
                ),
            ],
            options={
                "ordering": ["submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="readingportal",
            index=models.Index(fields=["slug"], name="reading_por_slug_196f48_idx"),
        ),
        migrations.AddConstraint(
            model_name="portalreading",
            constraint=models.UniqueConstraint(
                fields=("reading_portal", "language"), name="unique_language_per_portal"
            ),
        ),
        migrations.AddConstraint(
            model_name="readingsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reading_status", "pending")),
                fields=("reading_portal", "member", "language"),
                name="unique_pending_submission_per_lang_per_portal",
            ),
        ),
    ]
