# Generated by Django 6.0.2 on 2026-03-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reading_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="readingportal",
            options={"ordering": ["date_created"]},
        ),
    ]
