databases:
- name: nubladoproject
  databaseName: nubladoproject
  user: nubladoproject

services:
- type: web
  name: nubladoproject
  plan: free
  env: python
  buildCommand: "./build.sh"
  startCommand: "./start.sh"
  autoDeploy: false
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: nubladoproject
        property: connectionString
    - fromGroup: nubladoproject