# Generated by Django 4.0 on 2022-10-01 21:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TmpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('message_id', models.BigIntegerField()),
                ('chat_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'tmp message',
                'verbose_name_plural': 'tmp messages',
                'unique_together': {('message_id', 'chat_id')},
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.PositiveBigIntegerField()),
                ('group_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Group member',
                'verbose_name_plural': 'Group members',
                'unique_together': {('user_id', 'group_id')},
            },
        ),
    ]
