# Generated by Django 5.1.7 on 2026-01-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date created"),
        ),
    ]
